#!/bin/zsh
set -eu
root=${0:A:h:h}
test_dir=$(mktemp -d /private/tmp/psvr2-picker-tests.XXXXXX)
trap 'rm -rf "$test_dir"' EXIT
swiftc "$root/player/files.swift" "$root/tools/picker-files-tests.swift" -o "$test_dir/tests"
"$test_dir/tests"
